// ============================================================
// RTFOAM V11 — TWO-STAGE OPENAI DESIGN + VISUAL PROXY
// Required secret: OPENAI_API_KEY
// Optional variables: OPENAI_MODEL (gpt-5.6), OPENAI_REASONING_EFFORT (high), ALLOWED_ORIGIN
// The browser calls action="design" for engineering JSON and action="render_svg"
// for a second, vision-guided SVG art-direction pass.
// ============================================================
const DESIGN_SCHEMA={type:'object',additionalProperties:false,required:['name','description','rootChordMM','tipChordMM','sweepMM','targetWingLoadingGPerDM2','tailVolumeCoefficient','fuselageLengthMM','noseLengthMM','fuselageHeightMM','hStabSpanMM','hStabChordMM','vStabHeightMM','vStabChordMM','cgPercentMAC','weightG','architectureVariant','construction','visualBrief','notes'],properties:{name:{type:'string'},description:{type:'string'},rootChordMM:{type:'integer'},tipChordMM:{type:'integer'},sweepMM:{type:'integer'},targetWingLoadingGPerDM2:{type:'integer'},tailVolumeCoefficient:{type:'integer'},fuselageLengthMM:{type:'integer'},noseLengthMM:{type:'integer'},fuselageHeightMM:{type:'integer'},hStabSpanMM:{type:'integer'},hStabChordMM:{type:'integer'},vStabHeightMM:{type:'integer'},vStabChordMM:{type:'integer'},cgPercentMAC:{type:'integer'},weightG:{type:'integer'},architectureVariant:{type:'string'},construction:{type:'object',additionalProperties:false,required:['fuselageMethod','wingMethod','parts'],properties:{fuselageMethod:{type:'string'},wingMethod:{type:'string'},parts:{type:'array',minItems:8,maxItems:18,items:{type:'object',additionalProperties:false,required:['id','label','quantity','role'],properties:{id:{type:'string'},label:{type:'string'},quantity:{type:'integer'},role:{type:'string'}}}}}},visualBrief:{type:'object',additionalProperties:false,required:['silhouette','nose','wing','tail','distinctiveFeatures'],properties:{silhouette:{type:'string'},nose:{type:'string'},wing:{type:'string'},tail:{type:'string'},distinctiveFeatures:{type:'array',minItems:3,maxItems:8,items:{type:'string'}}}},notes:{type:'array',minItems:4,maxItems:6,items:{type:'string'}}}};
const VISUAL_SCHEMA={type:'object',additionalProperties:false,required:['dossierSvg','topSvg','explodedSvg','perspectiveSvg'],properties:{dossierSvg:{type:'string'},topSvg:{type:'string'},explodedSvg:{type:'string'},perspectiveSvg:{type:'string'}}};
export default {async fetch(request,env){const cors=makeCors(env.ALLOWED_ORIGIN||'*');if(request.method==='OPTIONS')return new Response(null,{headers:cors});if(request.method!=='POST')return json({error:'POST only'},405,cors);if(!env.OPENAI_API_KEY)return json({error:'OPENAI_API_KEY is not configured.'},500,cors);let body;try{body=await request.json()}catch{return json({error:'Bad JSON'},400,cors)}try{if(body.action==='render_svg')return await renderSvg(body,env,cors);return await design(body,env,cors)}catch(e){return json({error:String(e?.message||e)},500,cors)}}};
async function design(body,env,cors){const {system,messages}=body||{};if(!system||!Array.isArray(messages))return json({error:'Expected {system,messages}'},400,cors);const input=messages.map(m=>({role:m.role==='assistant'?'assistant':'user',content:[{type:'input_text',text:String(m.content||'')}]}));const result=await responses(env,{model:env.OPENAI_MODEL||'gpt-5.6',instructions:system,input,reasoning:{effort:env.OPENAI_REASONING_EFFORT||'high'},max_output_tokens:5000,text:{format:{type:'json_schema',name:'foam_aircraft_design',strict:true,schema:DESIGN_SCHEMA}}});return json({text:extractText(result),model:result.model,requestId:result.id},200,cors)}
async function renderSvg(body,env,cors){if(!body.design)return json({error:'Expected design'},400,cors);const instructions=`You are an expert aerospace technical illustrator and foam-board RC aircraft designer. Create four polished standalone SVG documents from the validated design JSON. The visual standard is a premium exploded assembly dossier like the supplied XW-1 reference: coherent aircraft identity, real construction parts, curved geometry, clear depth cues, dashed assembly paths, leaders that never cross text, and no clipped or overlapping labels. Do not reuse a generic needle fuselage. Every style must be unmistakable: TRAINER = box fuselage, high wing, generous tail and rounded tips; FIGHTER = pointed nose, swept/delta wing, compact body and appropriate fins/tail; EXPERIMENTAL = blended flying wing, equipment pod, twin fins, elevons; WARBIRD = full cowl/nose volume, canopy/deck, low wing with elliptical or clipped-elliptical planform, tapered rear fuselage and full tail. Use actual parts from construction.parts. The dossier SVG must use viewBox 0 0 1600 1060 on a warm white technical-document background and include specifications, large exploded view, large ready top view, perspective-like view, assembly sequence, symbols, CG, spar and servo callouts. Preview SVGs use viewBox 0 0 900 420. Use paths with cubic/quadratic curves for rounded forms. No raster images, scripts, foreignObject, external href, animation, CSS imports, or HTML. Return only the strict JSON fields. Keep each SVG concise but visually rich.`;
const content=[{type:'input_text',text:'VALIDATED DESIGN JSON:\n'+JSON.stringify(body.design)}];if(body.referenceImageUrl&&/^https:\/\//.test(body.referenceImageUrl))content.push({type:'input_image',image_url:body.referenceImageUrl});const result=await responses(env,{model:env.OPENAI_MODEL||'gpt-5.6',instructions,input:[{role:'user',content}],reasoning:{effort:'high'},max_output_tokens:18000,text:{format:{type:'json_schema',name:'rtfoam_visual_package',strict:true,schema:VISUAL_SCHEMA}}});const text=extractText(result);let visuals;try{visuals=JSON.parse(text)}catch{throw new Error('Visual model returned malformed JSON')}return json({visuals,model:result.model,requestId:result.id},200,cors)}
async function responses(env,payload){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+env.OPENAI_API_KEY},body:JSON.stringify(payload)});if(!r.ok)throw new Error('OpenAI '+r.status+': '+(await r.text()).slice(0,700));return r.json()}
function extractText(result){if(typeof result.output_text==='string'&&result.output_text.trim())return result.output_text;const chunks=[];for(const item of result.output||[])for(const part of item.content||[])if(part.type==='output_text'&&part.text)chunks.push(part.text);if(!chunks.length)throw new Error('OpenAI returned no output text.');return chunks.join('')}
function makeCors(origin){return {'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'content-type','Vary':'Origin'}}
function json(payload,status,cors){return new Response(JSON.stringify(payload),{status,headers:{'content-type':'application/json; charset=utf-8',...cors}})}
